export const PHYSICS_IGCSE = {
  id: 'physics-igcse',
  title: 'Physics',
  code: '0625 / 0972',
  category: 'IGCSE',
  notes: [
    {
      id: 'forces',
      title: 'Forces & Motion',
      subChapters: [
        {
          id: 'speed-velocity-acceleration',
          title: 'Speed, Velocity & Acceleration',
          downloadUrl: '#',
          content: [
            { type: 'heading', content: 'Understanding Motion' },
            { type: 'text', content: 'Speed is the distance travelled per unit time. Velocity is speed in a given direction.' },
            { type: 'image', url: 'https://picsum.photos/seed/physics1/800/400', caption: 'Motion diagrams' }
          ]
        }
      ]
    }
  ],
  topicalQuestions: [],
  textbooks: [],
  resources: []
};

export const PHYSICS_AL = {
  id: 'physics-al',
  title: 'Physics',
  code: '9702',
  category: 'A-Level',
  notes: [],
  noteResources: [
    { id: 'al-physics-combined-1', title: 'Combined Chapters Notes - 1', url: 'https://drive.google.com/file/d/1KFgAoEAbd7r-LcW9cjU36xN5L1j8HqWa/view?usp=sharing', type: 'pdf', category: 'Combined Chapters Notes' },
    { id: 'al-physics-combined-2', title: 'Combined Chapters Notes - 2', url: 'https://drive.google.com/file/d/1KFgAoEAbd7r-LcW9cjU36xN5L1j8HqWa/view?usp=sharing', type: 'pdf', category: 'Combined Chapters Notes' },
    { id: 'al-physics-combined-3', title: 'Combined Chapters Notes - 3', url: 'https://drive.google.com/file/d/1KFgAoEAbd7r-LcW9cjU36xN5L1j8HqWa/view?usp=sharing', type: 'pdf', category: 'Combined Chapters Notes' },
    { id: 'al-physics-combined-4', title: 'Combined Chapters Notes - 4', url: 'https://drive.google.com/file/d/15oP3OV9vU52O87_uKdVao48UZBhbEcIO/view?usp=drive_link', type: 'pdf', category: 'Combined Chapters Notes' },
    { id: 'al-physics-combined-5', title: 'Combined Chapters Notes - 5', url: 'https://drive.google.com/file/d/1_tkqvJaxAro6nmxL5b-a3BDmEWNRaU15/view?usp=sharing', type: 'pdf', category: 'Combined Chapters Notes' },
    { id: 'al-physics-combined-6', title: 'Combined Chapters Notes - 6', url: 'https://drive.google.com/file/d/1M6PPUCOY04PNnG7qBCwllHZKgr35ObT2/view?usp=sharing', type: 'pdf', category: 'Combined Chapters Notes' },
    { id: 'al-physics-defs-1', title: 'Definitions - 1', url: 'https://drive.google.com/file/d/1CuMRZSjamPZ6-OoM5CiE9c4KS6W5c7SK/view?usp=sharing', type: 'pdf', category: 'Definitions' },
    { id: 'al-physics-defs-2', title: 'Definitions - 2', url: 'https://drive.google.com/file/d/1GeRlCdvq-uFaAihO0hIK-KZw2Cc3KWkc/view?usp=sharing', type: 'pdf', category: 'Definitions' },
    { id: 'al-physics-formulas-1', title: 'Formulas/Equations - 1', url: 'https://drive.google.com/file/d/1Nnm4lJaVazZ5wd8Kr2pXWpacBy3XRfod/view?usp=sharing', type: 'pdf', category: 'Formulas/Equations' },
    { id: 'al-physics-formulas-2', title: 'Formulas/Equations - 2', url: 'https://drive.google.com/file/d/10jXYA80G1rv53pB4rg8pt9T-AhZLl0EB/view?usp=sharing', type: 'pdf', category: 'Formulas/Equations' },
    { id: 'al-physics-notes-deformation', title: 'Deformation of Solids', url: 'https://drive.google.com/file/d/14xD46W3kVqi7C595OYCLYLMn6nybKnlN/view?usp=drive_link', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-density', title: 'Density & Pressure', url: 'https://drive.google.com/file/d/14xD46W3kVqi7C595OYCLYLMn6nybKnlN/view?usp=sharing', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-circuits', title: 'Electric Circuits', url: 'https://drive.google.com/file/d/1nPdVNcB5Kkj322Galktlk9FthXe29-05/view?usp=sharing', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-general', title: 'General Physics', url: 'https://drive.google.com/file/d/1JneCEY0vN6Nr1rJZZOpSN6lZiW56K5ai/view?usp=drive_link', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-momentum', title: 'Momentum & Forces', url: 'https://drive.google.com/file/d/1WspUBIqvhGmW6OjITfilAr94pOY07-AD/view?usp=sharing', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-motion', title: 'Motion', url: 'https://drive.google.com/file/d/1CPC3BcQq2k7HhTznSTvgwR1gyQRMNRWW/view?usp=sharing', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-particle', title: 'Particle Physics', url: 'https://drive.google.com/file/d/1kN7ZVV-5YiznE7WuUr8hTk-oEyguCYFZ/view?usp=sharing', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-p3', title: 'Physics Paper 3', url: 'https://drive.google.com/file/d/1wGCXlINMp9-M22l_kjUYwCB2KK-6AEgl/view?usp=sharing', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-uncertainty', title: 'Uncertainty Calculations & Measurements', url: 'https://drive.google.com/file/d/1GptIiPrwfor1U4-_E5Og8co7W94yecOv/view?usp=sharing', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-waves', title: 'Waves', url: 'https://drive.google.com/file/d/1pihRTO2qf0y8Z-vre868_0z_T-2sWEsp/view?usp=sharing', type: 'pdf', category: 'Notes (Topic Wise)' },
    { id: 'al-physics-notes-work', title: 'Work, Energy & Power', url: 'https://drive.google.com/file/d/14dRFUQn_Vw93oTOp5c9uI_6_A_rgPzNy/view?usp=sharing', type: 'pdf', category: 'Notes (Topic Wise)' }
  ],
  topicalQuestions: [
    { title: 'Matter QP', url: 'https://drive.google.com/file/d/15FeGIQvgvJ_RZszCakA5PxezTviKPyJb/view?usp=drivesdk', type: 'pdf', category: 'Question Papers' },
    { title: 'Physical Quantities & Measure MS', url: 'https://drive.google.com/file/d/17cDBOyuw5BiJ6YoFRCSGneQO3BMJgMwp/view?usp=drivesdk', type: 'pdf', category: 'Mark Schemes' },
    { title: 'Work Energy Power MS', url: 'https://drive.google.com/file/d/19Y86WeJulTtS8u_JFL1kqe5ck8vaASR7/view?usp=drivesdk', type: 'pdf', category: 'Mark Schemes' },
    { title: 'Work Energy Power QP', url: 'https://drive.google.com/file/d/1NcsmwlgnusEgCMvARsXVpKC9OlPiy8xN/view?usp=drivesdk', type: 'pdf', category: 'Question Papers' },
    { title: 'Physical Quantities & Measure QP', url: 'https://drive.google.com/file/d/1Rkj6kDqMN2h__iLE-PQ3D_K0S7qw8OXO/view?usp=drivesdk', type: 'pdf', category: 'Question Papers' },
    { title: 'Radioactivity QP', url: 'https://drive.google.com/file/d/1Rn9DCu5ThGIMVhpTeUp8yARghWinvhuT/view?usp=drivesdk', type: 'pdf', category: 'Question Papers' },
    { title: 'Waves QP', url: 'https://drive.google.com/file/d/1UNX43EvwAms2u2OB1B8S8esj3L0LP5KS/view?usp=drivesdk', type: 'pdf', category: 'Question Papers' },
    { title: 'Radioactivity MS', url: 'https://drive.google.com/file/d/1gQSB6yNdlHSJeAYGwspUa3uai_DLVBx5/view?usp=drivesdk', type: 'pdf', category: 'Mark Schemes' },
    { title: 'MCQ Topical Questions', url: 'https://drive.google.com/file/d/1iQ2hGlwbma9XJIeTp53mVfyuLeqWPzAr/view?usp=drivesdk', type: 'pdf', category: 'General' },
    { title: 'Waves MS', url: 'https://drive.google.com/file/d/1x0OjXSlZ-WivQT8DLsbgcG5fr_VVh8Rx/view?usp=drivesdk', type: 'pdf', category: 'Mark Schemes' },
    { title: 'Deforming Solids QP', url: 'https://drive.google.com/file/d/11q1Lxfivg7A53nGbaqlelNQkXZSbUFof/view?usp=drivesdk', type: 'pdf', category: 'Question Papers' },
    { title: 'Forces Dynamics & Momentum QP', url: 'https://drive.google.com/file/d/11wmIS9XV4RHQEsf6UvfpN6s3lkgJpiVS/view?usp=drivesdk', type: 'pdf', category: 'Question Papers' },
    { title: 'Electricity MS', url: 'https://drive.google.com/file/d/12m3ctYPSDGoCp4KrJiVHAtVBSiPJHWPl/view?usp=drivesdk', type: 'pdf', category: 'Mark Schemes' },
    { title: 'Kinematics QP', url: 'https://drive.google.com/file/d/1BrjxdlmYLiCOI6IarAwlQZtn9-j_RmeQ/view?usp=drivesdk', type: 'pdf', category: 'Question Papers' },
    { title: 'Electricity QP', url: 'https://drive.google.com/file/d/1C9upIxyMEe55XWiHA1RQtkyJ9krj2Dbc/view?usp=drivesdk', type: 'pdf', category: 'Question Papers' },
    { title: 'Matter MS', url: 'https://drive.google.com/file/d/1DfCsZnt2Wh5Gxfhn0tl5Z4E4y_bpVqKn/view?usp=drivesdk', type: 'pdf', category: 'Mark Schemes' },
    { title: 'Forces Dynamics & Momentum MS', url: 'https://drive.google.com/file/d/1ZpMTmcVUxFeV1o7BRO2jewgPi8LEL2ZZ/view?usp=drivesdk', type: 'pdf', category: 'Mark Schemes' },
    { title: 'Kinematics MS', url: 'https://drive.google.com/file/d/1cyTEmq1up5PQRYWcYfL1Jn_Jd0EAmDKV/view?usp=drivesdk', type: 'pdf', category: 'Mark Schemes' },
    { title: 'Deforming Solids MS', url: 'https://drive.google.com/file/d/1r-U-pVsB5q7RiTqwK_7FlZoBJSThz7Ob/view?usp=drivesdk', type: 'pdf', category: 'Mark Schemes' },
    { title: 'Definition Questions', url: 'https://drive.google.com/file/d/1v4-OEXkTodH_SCoPxI8Xi9WVHR04KXut/view?usp=drivesdk', type: 'pdf', category: 'General' },
  ],
  textbooks: [
    { title: 'Study and Revision Guide 3rd Ed', description: 'Woodside & Williams', url: 'https://drive.google.com/file/d/1_OvKJVLhWMpKCV4stF7sDFvPCO-9N5Gg/view?usp=sharing', type: 'pdf' },
    { title: 'Coursebook 2nd Ed (2014)', description: 'Cambridge University Press', url: 'https://drive.google.com/file/d/192UzY-hO9fCtIsQWgCgmF2YK99vp33qj/view?usp=sharing', type: 'pdf' },
    { title: 'Coursebook 3rd Ed (2020)', description: 'Cambridge University Press', url: 'https://drive.google.com/file/d/1oOp8fiXj78xMWN3m-w7sinTW4wsm1LnC/view?usp=sharing', type: 'pdf' },
    { title: 'Students Book 3rd Ed', description: 'Sang, Jones, Woodside, Chadha', url: 'https://drive.google.com/file/d/1YGLMd5LxQIm2Kc5Cy7AKOjLgUhpISNre/view?usp=sharing', type: 'pdf' },
    { title: 'Exam Success in Physics AS-AL', description: 'Revision Guide', url: 'https://drive.google.com/file/d/1tZh1cCIZy7T2cimNoJc4KBlZY9EmSwqq/view?usp=sharing', type: 'pdf' },
    { title: 'Practical Workbook (2020)', description: 'Jones, Field, Hewlett, Styles', url: 'https://drive.google.com/file/d/158jb9ggB_9BAilHVnsSQdAEfLiduQiqP/view?usp=sharing', type: 'pdf' },
    { title: 'Physics Textbook 101', description: 'Reference Book', url: 'https://drive.google.com/file/d/1bzg-LlSgL3cvhfhrHe4IM8M-fZ_Qfw2S/view?usp=sharing', type: 'pdf' }
  ],
  resources: [
     { title: 'Physics Spreadsheet', url: '#', type: 'xlsx' },
  ]
};

export const CHEMISTRY_AL = {
  id: 'chemistry-al',
  title: 'Chemistry',
  code: '9701',
  category: 'A-Level',
  notes: [],
  noteResources: [
    { title: 'AS Physical Chemistry', url: 'https://drive.google.com/file/d/1-vJE6G0F9pusGQYC66PrJnN0eOgR_wPb/view?usp=drivesdk', category: 'General Notes' },
    { title: 'AS Organic Chemistry', url: 'https://drive.google.com/file/d/14dXKoRoC2QkHkhET_R04ySqQgzFQ9l1U/view?usp=drivesdk', category: 'General Notes' },
    { title: 'ZNOTES', url: 'https://drive.google.com/file/d/1O8eHc4NuKFjUyGjaGne_1fLbP8oHHilL/view?usp=drivesdk', category: 'General Notes' },
    { title: 'Things To Memorize', url: 'https://drive.google.com/file/d/1R-7fvKVyfwTFSAen_YKFyZ0cYkooJqQU/view?usp=drivesdk', category: 'Revision' },
    { title: 'AS Physical Chemistry - VSEPR', url: 'https://drive.google.com/file/d/1UqORt92eJKBuR70B2IWyFb8y82SwEZXn/view?usp=drivesdk', category: 'General Notes' },
    { title: 'AS Inorganic Chemistry', url: 'https://drive.google.com/file/d/1ZLKq7wLQhzB2Ptqh9PKtuOwQ04-asGY_/view?usp=drivesdk', category: 'General Notes' },
    { title: 'Definitions', url: 'https://drive.google.com/file/d/1cwtttOn44vUAC2YCUgGKtPaMeHl-kqVA/view?usp=drivesdk', category: 'Revision' },
    { title: 'All Reactions', url: 'https://drive.google.com/file/d/1jpF5-i-qYcM-buYwIwJOSMI4hoyjkbk0/view?usp=drivesdk', category: 'Revision' },
    { title: 'Revision List', url: 'https://drive.google.com/file/d/1oqFfrL38kE-GCgQIm8D_CWzSs_NUN02D/view?usp=drivesdk', category: 'Revision' },
    { title: 'AS Organic Chemistry (SME)', url: 'https://drive.google.com/file/d/105PpnyTQRFQImiU-7TecfdwP1LJJxdxQ/view?usp=drivesdk', category: 'SaveMyExams' },
    { title: 'AS Inorganic Chemistry (SME)', url: 'https://drive.google.com/file/d/1A10wBoVuxtuob2C71WrpU0YL5ihdJadM/view?usp=drivesdk', category: 'SaveMyExams' },
    { title: 'AS Analytic Notes (SME)', url: 'https://drive.google.com/file/d/1TVi-Qj4n0XMBg_ArsKryeTtU1tdkNI8F/view?usp=drivesdk', category: 'SaveMyExams' },
    { title: 'AS Physical Chemistry (SME)', url: 'https://drive.google.com/file/d/1gdY3ove7A_iKz_NZFo_Po6svExU21ewN/view?usp=drivesdk', category: 'SaveMyExams' },
    { title: 'Analytical Techniques', url: 'https://drive.google.com/file/d/128sMaes9cwUZYYCoSm_7nYdm5hCAzokK/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Organic Synthesis', url: 'https://drive.google.com/file/d/1rDRLKnVZfWTwKn2oARlQy9bUk8Iebhbj/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Carbonyl Compounds', url: 'https://drive.google.com/file/d/10VdJzKcOuIO4FUMi5CdBUqRXGfjSqBgf/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Nitrogen Sulfur', url: 'https://drive.google.com/file/d/18Z8IWkrGqVaVbKt1mbIF6r6htphFYOph/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Group 17', url: 'https://drive.google.com/file/d/1L7BXB7vep1d2ET1VFFtKV9-oB_Ctxx-2/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Polymerisation', url: 'https://drive.google.com/file/d/1LzS2Ecudzcok74Wl1kLJ5zmF8HXnxQxf/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Nitrogen Compounds', url: 'https://drive.google.com/file/d/1OEJn0LthZqTkQZqboMhwM741m23kUAOU/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Halogen Compounds', url: 'https://drive.google.com/file/d/1SWC3qfYtZeC__DghQpuTg0ULnicmwrBc/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Carboxylic Acids', url: 'https://drive.google.com/file/d/1WAubUobrYb33VXoO_3bdxPYmPu_RGD2a/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Hydrocarbons', url: 'https://drive.google.com/file/d/1sfT3aO2L6j1s42VjuGWtXzuyqxn0LyOG/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Intro to AS Organic', url: 'https://drive.google.com/file/d/1xvw6wWSVgoalglDyIlTgjYW6iMDrBdP4/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Hydroxy Compounds', url: 'https://drive.google.com/file/d/1zFkOgKM7CVswVqPUpEfQZEfvhQyN24yh/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Periodicity', url: 'https://drive.google.com/file/d/10m94Tv5-0_iri6BTMyb-_3Qar67YMXMa/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Reaction Kinetics', url: 'https://drive.google.com/file/d/1ArRI1tYMvUrWt6RUALDSB0ybeaV-qSKp/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Chemical Bonding', url: 'https://drive.google.com/file/d/1BMo87KOqEavY8P-HpyXB4Ahsdbz1iBOT/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Atomic Structure', url: 'https://drive.google.com/file/d/1CH9j2NhrWzPvF_YnJuK-j-IyFS58pr5O/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Equilibria', url: 'https://drive.google.com/file/d/1Nb9xF2PezdBEg081cOfbHFn0rx1MSKCd/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Group 2', url: 'https://drive.google.com/file/d/1c8NoLWL8hXWCYkmo9iTVADul9griuTiU/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Electrochemistry', url: 'https://drive.google.com/file/d/1lZqkjrYJ0MAwduJ-BkplB28WuJSa2NPA/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'States of Matter', url: 'https://drive.google.com/file/d/1nZg_REmHnj_GqnICj5dYwJDzvCiuIEsb/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Chemical Energetics', url: 'https://drive.google.com/file/d/1pRWj-xx0zdzjWEWR99QYuHnKvOcaJ0U9/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Atoms Moles Stoichiometry', url: 'https://drive.google.com/file/d/1yZZeZBQmg-uhV6zc6D4dtjUuIQx7y8Ra/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Organic Map 1', url: 'https://drive.google.com/file/d/1f5NtJwWHsAxiXNYAkX1-cN5L5LU6Dofg/view?usp=drivesdk', category: 'Maps' },
    { title: 'Organic Map 2', url: 'https://drive.google.com/file/d/1uG6Eop0qNRXw3OjCSZRuk9TqHBQEnAR7/view?usp=drivesdk', category: 'Maps' },
    { title: 'Organic Map 3', url: 'https://drive.google.com/file/d/1IyPuFi8aixDwVxEzdrraDPfEvNGq-J1n/view?usp=drivesdk', category: 'Maps' },
    { title: 'States of Matter Questions', url: 'https://drive.google.com/file/d/1ZPHYMIV2Z2RQqQX9ZvDwvp92m_6usTRK/view?usp=drivesdk', category: 'Common Questions' },
    { title: 'Inorganic Questions', url: 'https://drive.google.com/file/d/16EgBoyQErJPhKd8OFDwUvKaORPGVtTPR/view?usp=drivesdk', category: 'Common Questions' },
    { title: 'Chemical Bonding Questions', url: 'https://drive.google.com/file/d/17z8Gs2gYJhVtrkQ1vT22t_mx9V2-Xjw4/view?usp=drivesdk', category: 'Common Questions' },
    { title: 'Reaction Kinetics Questions 1', url: 'https://drive.google.com/file/d/1IlGzkcipHZMa1WoZFq8jdvXOuCaRu88z/view?usp=drivesdk', category: 'Common Questions' },
    { title: 'Reaction Kinetics Questions 2', url: 'https://drive.google.com/file/d/1Cjw4wCgr05kiafMm47QYS_ft6hi-NAMe/view?usp=drivesdk', category: 'Common Questions' },
    { title: 'Silly Mistakes', url: 'https://drive.google.com/file/d/1KkL6tSqGlO8PNlcDoxhtxHEmwAtQ26Cl/view?usp=drivesdk', category: 'Common Questions' },
    { title: 'Organic Common Questions', url: 'https://drive.google.com/file/d/1MOmpZHpRJpUgYlIfvHL7YtTq_ssc7FG8/view?usp=drivesdk', category: 'Common Questions' },
    { title: 'Difficult Questions 1', url: 'https://drive.google.com/file/d/1NNdO6mPQ1EY-L5iPCErYfIxBc-kCcc_2/view?usp=drivesdk', category: 'Common Questions' },
    { title: 'Difficult Questions 2', url: 'https://drive.google.com/file/d/1oaB__Mq5Ztu35a1fPKlcaicGQgz27_mk/view?usp=drivesdk', category: 'Common Questions' },
    { title: 'Paper 3 Guide', url: 'https://drive.google.com/file/d/1a1zqzkvef_U2TgYn_qCbjkYMUEjokGS7/view?usp=drivesdk', category: 'Exam Prep' },
    { title: 'Paper 1 Repeated Questions', url: 'https://drive.google.com/file/d/1eK7ZdomiNauKGebSabB-JquEzkhm-tYL/view?usp=drivesdk', category: 'Exam Prep' },
    { title: 'Chemistry Notes 1', url: 'https://drive.google.com/file/d/1L9pzgSiQrQbLY8v2D3x16YpD1TVlx5-q/view?usp=drivesdk', category: 'Combined' },
    { title: 'Chemistry Notes 2', url: 'https://drive.google.com/file/d/1QtTgwv44qFrWWJzROhSpoxR3-iL2oXjk/view?usp=drivesdk', category: 'Combined' },
    { title: 'Chemistry Notes 3', url: 'https://drive.google.com/file/d/18mJSuq8n0ifzN4xc_zluzDnuCfWILs-3/view?usp=drivesdk', category: 'Combined' },
    { title: 'Chemistry Notes 4', url: 'https://drive.google.com/file/d/1LUoinvfzSiMSSJuCOFecDAyb0JOJsK8p/view?usp=drivesdk', category: 'Combined' },
    { title: 'AS Chemistry Summary 1', url: 'https://drive.google.com/file/d/1aI_Ft0zP_lEtiFsUlMNJKMitbv7NE-c1/view?usp=drivesdk', category: 'Combined' },
    { title: 'AS Chemistry Summary 2', url: 'https://drive.google.com/file/d/1q6UIp_0y8XoDvLTrji5tw0LEUCa7f-7V/view?usp=drivesdk', category: 'Combined' },
  ],
  topicalQuestions: [
    { title: 'Paper 1 Topical Workbook (2022-24)', url: 'https://drive.google.com/file/d/12tiVB62JHEQOnj4MEkLoLhXpmFG0iy04/view?usp=drivesdk', category: 'Workbook' },
    { title: 'Paper 2 Topical Workbook (2022-24)', url: 'https://drive.google.com/file/d/1Sxe-eQwwpBoUDK3ovKbU30u117LAN5Bp/view?usp=drivesdk', category: 'Workbook' },
    { title: 'Paper 1 Topical Workbook (2019-21)', url: 'https://drive.google.com/file/d/1if1c92-65TEPBJYjOIVrQAmfAPAt3xgg/view?usp=drivesdk', category: 'Workbook' },
    { title: 'Paper 2 Topical Workbook (2019-21)', url: 'https://drive.google.com/file/d/1xEDK0NIhTRCZjAJLvdXTO950lEY1qKfn/view?usp=drivesdk', category: 'Workbook' },
    { title: 'Paper 1 Topical - 1', url: 'https://drive.google.com/file/d/1zpbIAdKFfES1t5qcUGS0927RN1k38MkN/view?usp=drivesdk', category: 'Single Topics' },
    { title: 'Paper 1 Topical - 2', url: 'https://drive.google.com/file/d/11or-7wDPhqzHMMCzV0M0Wh41TkB-YWTa/view?usp=drivesdk', category: 'Single Topics' },
    { title: 'Paper 2 Topical - 1', url: 'https://drive.google.com/file/d/1JES1Sxr5IDXuOXJb9y1c2BEPpUaQpz68/view?usp=drivesdk', category: 'Single Topics' },
    { title: 'Paper 2 Topical - 2', url: 'https://drive.google.com/file/d/1MqR8FLo3e6x3GHvLYQ9D9N72RIqpZYeR/view?usp=drivesdk', category: 'Single Topics' },
  ],
  textbooks: [
    { title: 'Coursebook (2020)', description: 'Lawrie Ryan & Roger Norris', url: 'https://drive.google.com/file/d/1V5J_0q7VexA9y-tdl4yE50QqO80cM15Y/view?usp=drivesdk' },
    { title: 'Coursebook (2014)', description: 'Lawrie Ryan & Roger Norris', url: 'https://drive.google.com/file/d/1yIKCWcs9WV_1CRB1dH8Lukax2gc6UWNI/view?usp=drivesdk' },
    { title: 'Students Book 2nd Ed', description: 'Graham Brown & Brian Sargent', url: 'https://drive.google.com/file/d/1agrKiKWnf-w8xVzKZDkszxhiNFQmmHRS/view?usp=drivesdk' },
    { title: 'Exam Success in Chemistry AS-AL', description: 'Revision Guide', url: 'https://drive.google.com/file/d/1mDGmJqm83Zs-5WDWQ1HAbQFedrJ9ORIt/view?usp=drivesdk' },
    { title: 'Chemistry in Context', description: 'AS-AL Reference', url: 'https://drive.google.com/file/d/1txzwR2sk3Nzrw3WB-58aSS8MXLSrhv4M/view?usp=drivesdk' },
  ],
  resources: [
     { title: 'Chemistry Spreadsheet', url: '#', type: 'xlsx' },
  ]
};

export const BIOLOGY_AL = {
  id: 'biology-al',
  title: 'Biology',
  code: '9700',
  category: 'A-Level',
  notes: [],
  noteResources: [
    { title: 'AS Biology Summary', url: 'https://drive.google.com/file/d/15J83TNNZBZiFrI0yqykhMQy7iN-m2jAm/view?usp=drivesdk', category: 'Combined' },
    { title: 'Eukaryotic Cells Labelling', url: 'https://drive.google.com/file/d/1TiM-PdNlVCi2-8S9PYf1bE9GPRftYQux/view?usp=drivesdk', category: 'Special Topics' },
    { title: 'AS Biology Notes 1', url: 'https://drive.google.com/file/d/1ZBw7fc6drnQgEZR3O5XVr-DNdH2RnZC0/view?usp=drivesdk', category: 'Combined' },
    { title: 'AS Biology Notes 2', url: 'https://drive.google.com/file/d/1ocMZWF6CADLmA8o3P1SfdTghRgNGU-KB/view?usp=drivesdk', category: 'Combined' },
    { title: 'AS Biology Hard Questions', url: 'https://drive.google.com/file/d/1qEtgJh1AfRsxmlh0nr9D0m6TDRo2xtiH/view?usp=drivesdk', category: 'Exam Prep' },
    { title: 'AS Revision Notes', url: 'https://drive.google.com/file/d/1qgwdaEYesCgMFKDaj1chmrF-YEBBBvIo/view?usp=drivesdk', category: 'Combined' },
    { title: 'Cell Structure', url: 'https://drive.google.com/file/d/1Ztof3cNJlHVcb2BIra7Hq7g6yGmUsM7K/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Biomolecules', url: 'https://drive.google.com/file/d/1AaZAooE4g2HRI_LpyjNDBgbvuhNMwFzY/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Enzymes', url: 'https://drive.google.com/file/d/1uRanoyFwUJPd3B-M8_r1noRFKPOHaoYu/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Cell Membranes', url: 'https://drive.google.com/file/d/1y3e0ihrsdXp5TCGPTWi1dg-HUjD9WAql/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Mitotic Cell Cycle', url: 'https://drive.google.com/file/d/1ellgvrXjWfeEQFxUC6bipcZlbya6JqvX/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Nucleic Acids', url: 'https://drive.google.com/file/d/1dIBU1fx6Z52yiJEiljnBWDs4dfAzt_17/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Transport in Plants', url: 'https://drive.google.com/file/d/1Yq9zs7dcuGjpgV1-241RfPVFvmYMLbNN/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Transport in Mammals', url: 'https://drive.google.com/file/d/1LdP_olT67tF9FFVIB2ERsbFrE9Kwj5CU/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Gas Exchange & Smoking', url: 'https://drive.google.com/file/d/1uN4Nl5PUnYFyM6Tx8vtL1hdLO_6wxx_I/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Infectious Diseases', url: 'https://drive.google.com/file/d/19vzgRFQqT61QVbM2ARxEw0oybN3e1tti/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Immunity', url: 'https://drive.google.com/file/d/1BFQtUUsluiJwB12EN75Ap302UJeL3X8E/view?usp=drivesdk', category: 'Topic Wise (Weebly)' },
    { title: 'Rocket Revise: Cell Structure', url: 'https://drive.google.com/file/d/1YEHOWWSrow1FPftB5zoRu8rUoIYjZ0L7/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Molecules', url: 'https://drive.google.com/file/d/1uFu0W70eDTdKO73BVvtxnNo28iJftNaM/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Enzymes', url: 'https://drive.google.com/file/d/1z7mLQrNdlsPJJlTGADpUUvsU-7yaQfp7/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Membranes', url: 'https://drive.google.com/file/d/1u1ndw0nRJ53YLSHJuvZHg1YKiNuH0HXO/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Mitosis', url: 'https://drive.google.com/file/d/1Em73s7mRaJ3jrEhv6LU6iyCjURPQXRxZ/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Nucleic Acids', url: 'https://drive.google.com/file/d/1oL64yLlgjzWEHv0A8UR2pKFAq21e8iWb/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Transport Plants', url: 'https://drive.google.com/file/d/1ViVtQ7Tgo8HGVleAD7qjP-Ib9uqWs6N9/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Transport Animals', url: 'https://drive.google.com/file/d/11kGuLJxSw4SM9C2rGhjCzzNt4_EONakG/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Gas Exchange', url: 'https://drive.google.com/file/d/1fn5yL6EPz4rnO5IlZqI6mecpu67hGcLC/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Diseases', url: 'https://drive.google.com/file/d/1-dETzGiGUlgkjkjNge0E5476BUZAXD2H/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Rocket Revise: Immunity', url: 'https://drive.google.com/file/d/1OCwPSOAbEu6cVNr0r8n5Pg6k3y6HAfyp/view?usp=drivesdk', category: 'Rocket Revise' },
    { title: 'Micrographs', url: 'https://drive.google.com/file/d/1LAQr80ad1FBtSaOEoIMZNjiEDKgfPDTE/view?usp=drivesdk', category: 'Paper 3' },
    { title: 'Paper 3 Revision Sheet', url: 'https://drive.google.com/file/d/1nyzjxEvU2q5oT9BPGepwgvNCLbbTKrTZ/view?usp=drivesdk', category: 'Paper 3' },
    { title: 'Paper 3 Guideline', url: 'https://drive.google.com/file/d/1S71AvHEMn5fBYL06BFEQkmWhIHokSoYI/view?usp=drivesdk', category: 'Paper 3' },
    { title: 'Paper 3 Instructions', url: 'https://drive.google.com/file/d/1fids8Jj-DOf1bIYn6QGdObhaPP_Vbipx/view?usp=drivesdk', category: 'Paper 3' },
    { title: 'Paper 3 Guide', url: 'https://drive.google.com/file/d/1hSkNzvuZ-aIwUnv2TNZUVUmHmtpHDpgl/view?usp=drivesdk', category: 'Paper 3' },
    { title: 'Paper 3 Notes 1-4', url: 'https://drive.google.com/file/d/1dFB2Gs1I3jSS9YduQud7Ct_3dR8uZm0b/view?usp=drivesdk', category: 'Paper 3' },
    { title: 'Paper 3 Diagrams 1-3', url: 'https://drive.google.com/file/d/1Q5hS9cgXzuGbdHr_YEyXk2CbJlMeBOO-/view?usp=drivesdk', category: 'Paper 3' },
  ],
  topicalQuestions: [],
  textbooks: [
    { title: 'Coursebook (Full Version)', description: 'Jones, Fosbery, Taylor etc.', url: 'https://pscE__wvrmRDKkgbQyy0iHiw3Hz1TcRQ/view?usp=drivesdk' },
    { title: 'Students Book 2nd Ed', description: 'Clegg & Goodwin', url: 'https://drive.google.com/file/d/1h6WVfqgSXK8XYO0M2MLNy7Z-frqioxIl/view?usp=drivesdk' },
    { title: 'Study & Revision Guide', description: 'Mary Jones', url: 'https://drive.google.com/file/d/1oHYJeqyYd5HCTsZhMbckxiWXF9m5oRhs/view?usp=drivesdk' },
    { title: 'Exam Success in Biology AS-AL', description: 'Revision Guide', url: 'https://drive.google.com/file/d/1_tzWBPg_58nA_h3wCQhSzlQ4TPv-V99d/view?usp=drivesdk' },
  ],
  resources: [
     { title: 'Biology Spreadsheet', url: '#', type: 'xlsx' },
  ]
};

export const MATH_IGCSE = { id: 'math-igcse', title: 'Mathematics', code: '0580 & 0980', category: 'IGCSE', notes: [], topicalQuestions: [], textbooks: [], resources: [{ title: 'Math Spreadsheet', url: '#', type: 'xlsx' }] };
export const BIOLOGY_IGCSE = { id: 'biology-igcse', title: 'Biology', code: '0610 & 0970', category: 'IGCSE', notes: [], topicalQuestions: [], textbooks: [], resources: [{ title: 'Biology Spreadsheet', url: '#', type: 'xlsx' }] };
export const CHEMISTRY_IGCSE = { id: 'chemistry-igcse', title: 'Chemistry', code: '0610 & 0971', category: 'IGCSE', notes: [], topicalQuestions: [], textbooks: [], resources: [{ title: 'Chemistry Spreadsheet', url: '#', type: 'xlsx' }] };
export const ICT_IGCSE = { id: 'ict-igcse', title: 'ICT', code: '0417', category: 'IGCSE', notes: [], topicalQuestions: [], textbooks: [], resources: [{ title: 'ICT Spreadsheet', url: '#', type: 'xlsx' }] };
export const IT_AL = { id: 'it-al', title: 'IT', code: '9626', category: 'A-Level', notes: [], topicalQuestions: [], textbooks: [], resources: [{ title: 'IT Spreadsheet', url: '#', type: 'xlsx' }] };
export const MATH_AL = { id: 'math-al', title: 'Mathematics', code: '9709', category: 'A-Level', notes: [], topicalQuestions: [], textbooks: [], resources: [{ title: 'Math Spreadsheet', url: '#', type: 'xlsx' }] };

export const CURRICULUM_DATA = {
  'physics-igcse': PHYSICS_IGCSE,
  'math-igcse': MATH_IGCSE,
  'biology-igcse': BIOLOGY_IGCSE,
  'chemistry-igcse': CHEMISTRY_IGCSE,
  'ict-igcse': ICT_IGCSE,
  'chemistry-al': CHEMISTRY_AL,
  'biology-al': BIOLOGY_AL,
  'physics-al': PHYSICS_AL,
  'it-al': IT_AL,
  'math-al': MATH_AL,
};

export const SUBJECTS_LIST = [
  { id: 'math-igcse', title: 'Mathematics', code: '0580 & 0980', category: 'IGCSE', icon: 'calculator' },
  { id: 'biology-igcse', title: 'Biology', code: '0610 & 0970', category: 'IGCSE', icon: 'dna' },
  { id: 'chemistry-igcse', title: 'Chemistry', code: '0610 & 0971', category: 'IGCSE', icon: 'flask-conical' },
  { id: 'ict-igcse', title: 'ICT', code: '0417', category: 'IGCSE', icon: 'monitor' },
  { id: 'physics-igcse', title: 'Physics', code: '0625 / 0972', category: 'IGCSE', icon: 'zap' },
  { id: 'chemistry-al', title: 'Chemistry', code: '9701', category: 'A-Level', icon: 'flask-conical' },
  { id: 'biology-al', title: 'Biology', code: '9700', category: 'A-Level', icon: 'dna' },
  { id: 'physics-al', title: 'Physics', code: '9702', category: 'A-Level', icon: 'zap' },
  { id: 'it-al', title: 'IT', code: '9626', category: 'A-Level', icon: 'database' },
  { id: 'math-al', title: 'Mathematics', code: '9709', category: 'A-Level', icon: 'calculator' },
];
